server:
  port: 10091

spring:
  application:
    name: spring-caching-with-redis
  datasource:
    url: jdbc:h2:mem:testRedisDB;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  cache:
    cache-names: billionaires
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 60000ms
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms

---
spring:
  profiles: test